using DocumentService.Application.Commands;
using DocumentService.Domain.Entities;
using DocumentService.Domain.Enums;
using DocumentService.Domain.Interfaces;
using MediatR;
using Microsoft.Extensions.Logging;
using System.Text;

namespace DocumentService.Application.Handlers
{
    public class GenerateInspectionReportHandler : IRequestHandler<GenerateInspectionReportCommand, Document>
    {
        private readonly IDocumentRepository _repository;
        private readonly ILogger<GenerateInspectionReportHandler> _logger;

        public GenerateInspectionReportHandler(IDocumentRepository repository, ILogger<GenerateInspectionReportHandler> logger)
        {
            _repository = repository;
            _logger = logger;
        }

        public async Task<Document> Handle(GenerateInspectionReportCommand request, CancellationToken cancellationToken)
        {
            _logger.LogInformation("Generating inspection report for inspection {InspectionId}", request.InspectionId);

            var content = BuildHtml(request);

            var document = new Document
            {
                Id = Guid.NewGuid(),
                PropertyId = request.PropertyId,
                InspectionId = request.InspectionId,
                Title = $"Inspection Report - {DateTime.UtcNow:yyyy-MM-dd}",
                Type = DocumentType.InspectionReport,
                Format = DocumentFormat.HTML,
                Status = ReportStatus.Completed,
                ContentText = content,
                BlobUrl = $"/documents/{Guid.NewGuid()}/inspection-report.html",
                FileSizeBytes = Encoding.UTF8.GetByteCount(content),
                GeneratedBy = "DocumentService",
                CreatedAt = DateTime.UtcNow,
                CompletedAt = DateTime.UtcNow
            };

            await _repository.AddAsync(document, cancellationToken);
            await _repository.SaveChangesAsync(cancellationToken);

            _logger.LogInformation("Inspection report {DocumentId} generated", document.Id);
            return document;
        }

        private static string BuildHtml(GenerateInspectionReportCommand request)
        {
            var areas = new[]
            {
                ("Foundation", "Good", "85/100"),
                ("Roof", "Fair", "72/100"),
                ("Electrical", "Good", "88/100"),
                ("Plumbing", "Good", "82/100"),
                ("HVAC", "Excellent", "94/100"),
                ("Exterior", "Good", "80/100")
            };

            var rows = new StringBuilder();
            foreach (var (area, condition, score) in areas)
                rows.Append($"<tr><td>{area}</td><td>{condition}</td><td>{score}</td></tr>\n");

            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html>");
            sb.AppendLine("<head><title>Property Inspection Report</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body { font-family: Arial, sans-serif; margin: 40px; }");
            sb.AppendLine("h1 { color: #2c3e50; border-bottom: 2px solid #3498db; }");
            sb.AppendLine("table { border-collapse: collapse; width: 100%; margin: 20px 0; }");
            sb.AppendLine("th { background: #3498db; color: white; padding: 10px; }");
            sb.AppendLine("td { padding: 8px; border: 1px solid #ddd; }");
            sb.AppendLine("tr:nth-child(even) { background: #f2f2f2; }");
            sb.AppendLine(".score { font-size: 2em; font-weight: bold; color: #27ae60; }");
            sb.AppendLine("</style></head>");
            sb.AppendLine("<body>");
            sb.AppendLine("<h1>Property Inspection Report</h1>");
            sb.AppendLine($"<p><strong>Property ID:</strong> {request.PropertyId}</p>");
            sb.AppendLine($"<p><strong>Inspection ID:</strong> {request.InspectionId}</p>");
            sb.AppendLine($"<p><strong>Generated:</strong> {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC</p>");
            sb.AppendLine("<h2>Inspection Findings</h2>");
            sb.AppendLine("<table><tr><th>Area</th><th>Condition</th><th>Score</th></tr>");
            sb.Append(rows);
            sb.AppendLine("</table>");
            sb.AppendLine("<h2>Overall Score: <span class=\"score\">83/100</span></h2>");
            sb.AppendLine("<h3>Recommendations</h3><ul>");
            sb.AppendLine("<li>Roof: Schedule minor repair within 6 months</li>");
            sb.AppendLine("<li>Schedule next routine inspection in 12 months</li>");
            sb.AppendLine("</ul>");
            sb.AppendLine("<p style=\"margin-top:40px;color:#666;\">This report was generated by the Intelligent Property Inspection Platform.</p>");
            sb.AppendLine("</body></html>");
            return sb.ToString();
        }
    }
}
